apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-case-controller
  labels:
    app: test-case-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-case-controller
  template:
    metadata:
      labels:
        app: test-case-controller
    spec:
      containers:
      - name: test-case-controller
        image: nazirlia/selenium-test-cases-chrome-node:v1  
        ports:
        - containerPort: 4444
        env:
        - name: HUB_HOST  
          value: selenium-hub
